---
# Root password
bootstrap__root_pass: '{{lookup("bitwarden", "root-pass")}}'
# Consul
bootstrap__consul_encryption_key: '{{lookup("bitwarden", "consul/cluster", field="encryption-key")}}'
bootstarp__consul_agent_acl_token: '{{lookup("bitwarden", "consul/acl-tokens", field="agent-default")}}'
# Wireguard
wireguard_consul_acl_token: '{{lookup("bitwarden", "consul/acl-tokens", field="wireguard")}}'

# Narrow users for host
bootstrap__active_extra_users:
  - { name: jarrad,  uid: 7030, groups: [], key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwNIJ07rCf23WJYPHBAU2PGhGuWrvx8Zu8eguiyaxtk2QN+bGQ0FBUCTl7CyJGtSckEF06u2JvaUj7qdfzNnxUZbppZCKwLh9hcLGEM0cU54SHrOl9akcPjMDNuOHWomPPIxLzmUDwjBlryYLTSjijf07BVeY2dEzVyWneU+a9RHbkUt6L2uKDTF1VYSK165GDDQrFTZFrgsJ0Zjm4xCSyFtK6ChwnLmF/ECpn1W8t1LzWdX/5QgcC7ohUPfxupGq2PG0cLiqR2RSSt23G1FKgCxKaJNh2okRwwZgIccMN8uovKxSJp9DwwLVAkU9HVS5EAZhIf1jFLdDVKWRfUfBn me@jarradhope.com' }

# CloudFlare Origin certificates
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("bitwarden", "Cloudflare/status.im", file="origin.crt")}}'
    key: '{{lookup("bitwarden", "Cloudflare/status.im", file="origin.key")}}'

# Master password for backups
restic_repo_master_pass: '{{lookup("bitwarden", "restic-backups/repo", field="master-pass")}}'
restic_ssh_public_key: '{{lookup("bitwarden", "restic-backups/ssh", field="public")}}'

# general container config
cont_state: started
cont_recreate: false
cont_restart: false
