---
- name: Configure Referral service host
  hosts: referral
  roles:
    - { role: origin-certs,     tags: origin-certs }
    - { role: swap-file,        tags: swap-file }
    - { role: referral-service, tags: referral-service }
    - { role: nginx,            tags: nginx }
    - { role: threatstack,      tags: threatstack }
