---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure Referral service host
  hosts: referral
  roles:
    - { role: origin-certs,     tags: origin-certs }
    - { role: swap-file,        tags: swap-file }
    - { role: referral-service, tags: referral-service }
    - { role: restic-backups,   tags: restic-backups }
    - { role: nginx,            tags: nginx }
    - { role: open-ports,       tags: open-ports }
    - { role: nginx-metrics,    tags: nginx-metrics }
    - { role: threatstack,      tags: threatstack, when: stage == "prod" }
