---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: nginx-metrics
  src: git@github.com:status-im/infra-role-nginx-metrics.git
  version: c0bc0325c11a4f1a5692b6d61efe5bde8c33aa41
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f2b061da8976444d6576b755578f0e799cde4372
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 7f2d730d60a3efc9e5e96e4c55490b7f9e0fd70e
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: dd70ea358b3e71f01a29766a93efb1fa40494a65
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 3427d5cc8dddff490ab982f51ec4b8cee88ccae3
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 4d7c9c606f5e039a22c34ba93961d05056c0e002
  scm: git

- name: threatstack
  src: git@github.com:status-im/infra-role-threatstack.git
  version: 581bf6f1bd8b0d4873a77166b9ceb48a417565eb
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: 15fadc81c5bf709be3e0d6071cebb6d6d8287ea0
  scm: git

- name: restic-backups
  src: git@github.com:status-im/infra-role-restic-backups.git
  version: 847398b1cec002324368eea6f21fc9952c084a45
  scm: git
