---
- name: Create timer for PostgreSQL DB dump
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: '{{ referral_srv_db_backup_name }}'
    systemd_timer_description: 'Dump Referral PostgreSQL database.'
    systemd_timer_user: '{{ referral_srv_db_backup_user }}'
    systemd_timer_frequency: '{{ referral_srv_db_backup_frequency }}'
    systemd_timer_timeout_sec: '{{ referral_srv_db_backup_timeout }}'
    systemd_timer_after_extra: '{{ referral_srv_db_backup_after }}'
    systemd_timer_start_on_creation: false
    systemd_timer_script_content: |
      #!/usr/bin/env bash
      BKP_DIR="{{ referral_srv_db_vol }}/backup/{{ referral_srv_db_name }}"
      rm -vfr "${BKP_DIR}"
      /usr/bin/docker exec -i -e PGPORT={{ referral_srv_db_port }} {{ referral_srv_db_cont_name }} \
        pg_dump -F directory -f "/backup/{{ referral_srv_db_name }}" \
        -U {{ referral_srv_db_user }} {{ referral_srv_db_name }}
      chmod 750 -R "${BKP_DIR}"
