---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ referral_srv_service_name }}'
    consul_services:
      - name: '{{ referral_srv_service_name }}'
        tags: ['referral', 'purchase']
        # we advertise the port with basic auth
        port: '{{ referral_srv_app_port }}'
        checks:
          - id: '{{ referral_srv_service_name }}-health'
            name: Referral Service Healthcheck
            type: http
            http: 'http://localhost:{{ referral_srv_app_port }}/health'
