---
- name: 'Create compose file: {{ referral_srv_service_name }}'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ referral_srv_service_compose }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create containers: {{ referral_srv_service_name }}'
  docker_compose:
    project_src: '{{ referral_srv_service_path }}'
    state: '{{ compose_state }}'
    recreate: '{{ compose_recreate or app_env.changes or db_env.changed }}'
    restarted: '{{ compose_restart }}'
    pull: true
    build: false

# Migrations need to run before the app
- name: 'Run migrations: {{ referral_srv_service_name }}'
  command: 'docker exec {{ referral_srv_app_name }} rake db:migrate'
