---
- name: Create container folders
  file:
    path: '{{ item }}'
    owner: dockremap
    group: docker
    state: directory
  with_items:
    - '{{ referral_srv_service_path }}'
    - '{{ referral_srv_app_vol }}'
    - '{{ referral_srv_cache_vol }}'

- name: Create database folder
  file:
    path: '{{ referral_srv_db_vol }}'
    owner: '{{ referral_srv_db_host_uid }}'
    group: '{{ referral_srv_db_host_uid }}'
    mode: 0777
    state: directory
    recurse: true

- name: Create env file for app
  template:
    src: 'app.env.j2'
    dest: '{{ referral_srv_service_path }}/app.env'
    group: docker
    mode: 0640
  register: app_env

- name: Create env file for db
  template:
    src: 'db.env.j2'
    dest: '{{ referral_srv_service_path }}/db.env'
    group: docker
    mode: 0640
  register: db_env
