---
- name: Create container folders
  file:
    path: '{{ item }}'
    owner: dockremap
    group: docker
    state: directory
  with_items:
    - '{{ referral_srv_service_path }}'
    - '{{ referral_srv_app_vol }}'
    - '{{ referral_srv_cache_vol }}'

- name: Create database folder
  file:
    path: '{{ referral_srv_db_vol }}'
    owner: '{{ referral_srv_db_host_uid }}'
    group: docker
    mode: 0777
    state: directory

- name: Create env file for app
  template:
    src: 'app.env.j2'
    dest: '{{ referral_srv_service_path }}/app.env'
    mode: 0640

- name: Create env file for db
  template:
    src: 'db.env.j2'
    dest: '{{ referral_srv_service_path }}/db.env'
    mode: 0640

- name: Create the Google Auth JSON file
  copy:
    dest: '{{ referral_srv_app_vol }}/{{ referral_srv_google_auth_json_file }}'
    content: '{{ referral_srv_google_auth_json | mandatory }}'
    mode: 0640
